# Generated by Django 4.0.4 on 2022-06-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
    ]
